### ISSUE TITLE
Draw up an intro

### ISSUE THREAD

**Issue by Putrya-Anton** [Putrya-Anton/homepage#4]
Дисклеймер: Нажаль, мій рівень знання англійської мови на цей час залишае бажати кращого, тому я заздалегіть прошу вибачення у шановного Рю за опис українською.

Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by mr-Collaborator** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.
