### ISSUE TITLE
Draw up a contact information block

### ISSUE THREAD

**Issue by Putrya-Anton** [Putrya-Anton/homepage#5]
Дисклеймер: Нажаль, мій рівень знання англійської мови на цей час залишае бажати кращого, тому я заздалегіть прошу вибачення у шановного Рю за опис українською.

Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by mr-Collaborator** [comment]
Ryu Hoshi (リュウ Ryū)
https://www.facebook.com/profile.php?id=100004808958030
ryuwins@gmail.com
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
